// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

/// @title DisclosureLattice
/// @notice The disclosure lattice, executable.
///
/// Background. The research carried the disclosure model as `G x O x T`
/// (granularity by observers by time) and BP-1 already recorded that it is a
/// dependent sum rather than a product. What was never settled is what the
/// *join* is, and the collusion checker in `scripts/collusion-check.py` answered
/// it with an ad hoc pair rule: take the greatest granularity any observer
/// reaches, and the earliest time at which that granularity is reached.
///
/// That rule is the lexicographic maximum on `G x T^op`. Lex order on two finite
/// chains is a total order, so it is a lattice and the checker's join is
/// well defined, associative and commutative. It is also **wrong**, in a
/// direction that produces false negatives. See `test/DisclosureLattice.t.sol`,
/// `test_lexJoinUnderReports`, which exhibits a witness.
///
/// The correct object is the lattice of order ideals of `G x T^op`, by Birkhoff's
/// representation theorem. A disclosure cell is not a point, it is the
/// downward closed set of everything the observer can therefore deduce. Join is
/// union, meet is intersection, order is inclusion, and the lattice is
/// distributive because it is a ring of sets.
///
/// This is cheap. `|G| = 5` and `|T| = 6`, so an ideal is a subset of a thirty
/// element poset and fits in a `uint32`. Join is one `OR`. The order test is one
/// `OR` and one comparison. The whole model runs on chain for a handful of gas,
/// which is what makes it a mechanism rather than a document.
///
/// Axis orientation, stated once because the two axes point opposite ways in the
/// prose. Granularity ascends with disclosure: `none` reveals least, `exact`
/// most. Time as written in BUILD-PLAN section 7.1 ascends with *delay*: `pre`
/// is seen before the fact and `never` is not seen at all, so time ascends with
/// secrecy. The poset order used here is disclosure strength throughout, so the
/// time axis is reversed: `(g, t) <= (g', t')` when `g <= g'` and `t >= t'`.
library DisclosureLattice {
    // ---------------------------------------------------------------- axes

    /// Granularity chain, ascending in disclosure. `none < pred < agg < bucket < exact`.
    uint8 internal constant G_NONE = 0;
    uint8 internal constant G_PRED = 1;
    uint8 internal constant G_AGG = 2;
    uint8 internal constant G_BUCKET = 3;
    uint8 internal constant G_EXACT = 4;
    uint8 internal constant G_CARD = 5;

    /// Time chain as written in section 7.1, ascending in delay.
    /// `pre < imm < +15m < EOD < epoch < never`.
    uint8 internal constant T_PRE = 0;
    uint8 internal constant T_IMM = 1;
    uint8 internal constant T_15M = 2;
    uint8 internal constant T_EOD = 3;
    uint8 internal constant T_EPOCH = 4;
    uint8 internal constant T_NEVER = 5;
    uint8 internal constant T_CARD = 6;

    /// All thirty cells set. The top of the lattice: everything, before the fact.
    uint32 internal constant TOP = 0x3FFFFFFF;
    /// No cell set. The bottom: nothing is learned at any time.
    uint32 internal constant BOTTOM = 0;

    /// Six bits, one row of the time axis.
    uint32 private constant ROW = 0x3F;

    error BadGranularity(uint8 g);
    error BadTime(uint8 t);
    error NotAnIdeal(uint32 x);

    // ------------------------------------------------------- construction

    /// @notice The principal ideal generated by one disclosure `(g, t)`.
    /// @dev An observer who learns `g` at `t` also, trivially, learns anything
    ///      coarser and anything later. The cell is that whole set, which is why
    ///      union is the right join: two observers pool their deductions.
    function point(uint8 g, uint8 t) internal pure returns (uint32) {
        if (g >= G_CARD) revert BadGranularity(g);
        if (t >= T_CARD) revert BadTime(t);
        // Times at or after `t`, within one row.
        uint32 later = ROW & ~((uint32(1) << t) - 1);
        // Repeat that row for granularities 0..g. In base 64 this is a repunit,
        // so `(2^(6(g+1)) - 1) / 63` is `1 + 2^6 + ... + 2^(6g)`.
        uint32 rows = uint32(((uint256(1) << (6 * (uint256(g) + 1))) - 1) / 63);
        return later * rows;
    }

    /// @notice The cell for an observer who learns nothing. Bottom.
    function nothing() internal pure returns (uint32) {
        return BOTTOM;
    }

    // -------------------------------------------------- lattice operations

    /// @notice Join. What a coalition of observers holds between them.
    /// @dev Union of ideals. Closed under downward closure, so the result is an
    ///      ideal whenever both arguments are.
    function join(uint32 a, uint32 b) internal pure returns (uint32) {
        return a | b;
    }

    /// @notice Meet. What two observers both hold.
    function meet(uint32 a, uint32 b) internal pure returns (uint32) {
        return a & b;
    }

    /// @notice `a <= b` in the lattice, that is, `b` discloses at least as much.
    function leq(uint32 a, uint32 b) internal pure returns (bool) {
        return a | b == b;
    }

    /// @notice The check the venue actually runs. True when `actual` stays under
    ///         the policy `ceiling`.
    /// @dev One OR and one comparison. This is the gate that makes a matrix cell
    ///      enforceable rather than aspirational.
    function permits(uint32 ceiling, uint32 actual) internal pure returns (bool) {
        return actual | ceiling == ceiling;
    }

    /// @notice The part of `actual` that exceeds `ceiling`. Empty iff permitted.
    /// @dev Returned rather than a bare bool so a revert can name the cells that
    ///      broke the policy, which is what makes a violation debuggable.
    function excess(uint32 ceiling, uint32 actual) internal pure returns (uint32) {
        return actual & ~ceiling;
    }

    // ------------------------------------------------------------ hygiene

    /// @notice Downward closure of an arbitrary bitmask.
    /// @dev Used to validate stored policies. A policy that is not an ideal is a
    ///      policy that claims an observer can know an exact value but not the
    ///      bucket it falls in, which is not a coherent disclosure.
    function close(uint32 x) internal pure returns (uint32) {
        uint32 out = 0;
        for (uint8 g = 0; g < G_CARD; ++g) {
            for (uint8 t = 0; t < T_CARD; ++t) {
                if (x & (uint32(1) << (g * T_CARD + t)) != 0) {
                    out |= point(g, t);
                }
            }
        }
        return out;
    }

    function isIdeal(uint32 x) internal pure returns (bool) {
        return x <= TOP && close(x) == x;
    }

    function requireIdeal(uint32 x) internal pure {
        if (!isIdeal(x)) revert NotAnIdeal(x);
    }

    // --------------------------------------------------------- projections

    /// @notice The greatest granularity anywhere in the ideal, and the earliest
    ///         time at which that granularity appears.
    /// @dev This is the lex summary the Python checker computes. It is exposed
    ///      only so the two can be compared, and it is lossy: see
    ///      `test_lexJoinUnderReports`. Do not gate on it.
    function lexSummary(uint32 x) internal pure returns (uint8 g, uint8 t, bool any) {
        for (uint8 gi = G_CARD; gi > 0; --gi) {
            uint32 row = (x >> ((gi - 1) * T_CARD)) & ROW;
            if (row != 0) {
                for (uint8 ti = 0; ti < T_CARD; ++ti) {
                    if (row & (uint32(1) << ti) != 0) {
                        return (gi - 1, ti, true);
                    }
                }
            }
        }
        return (0, 0, false);
    }

    /// @notice The earliest time at which anything at all is learned.
    /// @dev The projection R14 and R16 care about. A ceiling stated only in
    ///      granularity cannot express "not before end of day", which is the
    ///      defect the ideal representation removes.
    function earliest(uint32 x) internal pure returns (uint8 t, bool any) {
        for (uint8 ti = 0; ti < T_CARD; ++ti) {
            uint32 col = 0;
            for (uint8 gi = 0; gi < G_CARD; ++gi) {
                col |= (x >> (gi * T_CARD + ti)) & 1;
            }
            if (col != 0) return (ti, true);
        }
        return (0, false);
    }
}
