import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { resolve } from "node:path";

// IIFE so the generated landing page can load one file with a classic script
// tag. The venue's other screens stay bundler-free; this is the exception,
// and only because Three.js cannot be inlined the way keccak.mjs is.
export default defineConfig({
  plugins: [react()],
  define: {
    "process.env.NODE_ENV": JSON.stringify("production"),
  },
  build: {
    lib: {
      entry: resolve(__dirname, "src/mount.tsx"),
      name: "SeamGlass",
      formats: ["iife"],
      fileName: () => "glass.js",
    },
    outDir: resolve(__dirname, "../app"),
    emptyOutDir: false,
    sourcemap: false,
    minify: "esbuild",
    rollupOptions: {
      output: {
        inlineDynamicImports: true,
        entryFileNames: "glass.js",
        assetFileNames: "glass.[ext]",
        banner: "/* SeamMe glass layer. Generated by venue/glass. Do not edit. */",
      },
    },
  },
});
