// Builds the live screens (and the door page) from templates.
// Reads deployments/client.json and deployments/abi/*; writes tools/client-bundle.mjs
// then inlines via tools/gen-page.mjs. Does not edit existing generators or Solidity.
//
// Every exported ABI is bundled, not a chosen subset. A client that binds to
// five of the thirteen deployed contracts cannot tell you the venue is
// suspended, and the missing shape is never the one you expected to miss.
import {readFileSync, writeFileSync, mkdirSync, readdirSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";
import {build} from "./gen-page.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const abiDir = join(root, "deployments/abi");
const names = readdirSync(abiDir).filter((f) => f.endsWith(".json")).map((f) => f.slice(0, -5)).sort();

// `internalType` is documentation. ethers reads named tuple members off
// `components[].name`, so dropping it changes nothing a screen can observe and
// takes a quarter off the weight of carrying every ABI.
const strip = (x) =>
    Array.isArray(x) ? x.map(strip)
        : (x && typeof x === "object"
            ? Object.fromEntries(Object.entries(x)
                .filter(([k]) => k !== "internalType")
                .map(([k, v]) => [k, strip(v)]))
            : x);

const client = JSON.parse(readFileSync(join(root, "deployments/client.json"), "utf8"));
const abis = {};
for (const name of names) {
    abis[name] = strip(JSON.parse(readFileSync(join(abiDir, name + ".json"), "utf8")));
}

// Every contract address the client can read history for, so a screen naming a
// contract can also name what that contract did. The mirror node takes an EVM
// address as the path segment, so no entity id table has to be kept in step.
const bundle =
    "// Generated by tools/gen-app.mjs. Do not hand edit.\n" +
    "const CLIENT = " + JSON.stringify(client) + ";\n" +
    "const ABI = " + JSON.stringify(abis) + ";\n";

writeFileSync(join(root, "tools/client-bundle.mjs"), bundle);
mkdirSync(join(root, "app"), {recursive: true});

for (const name of ["index", "prove", "trade", "position", "venue", "repo"]) {
    build("app/" + name + ".template.html", "app/" + name + ".html");
}
