// Builds the live screens (and the door page) from templates.
// Reads deployments/client.json and deployments/abi/*; writes tools/client-bundle.mjs
// then inlines via tools/gen-page.mjs. Does not edit existing generators or Solidity.
//
// Every exported ABI is bundled, not a chosen subset. A client that binds to
// five of the thirteen deployed contracts cannot tell you the venue is
// suspended, and the missing shape is never the one you expected to miss.
import {readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";
import {build} from "./gen-page.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const abiDir = join(root, "deployments/abi");
const names = readdirSync(abiDir).filter((f) => f.endsWith(".json")).map((f) => f.slice(0, -5)).sort();

// `internalType` is documentation. ethers reads named tuple members off
// `components[].name`, so dropping it changes nothing a screen can observe and
// takes a quarter off the weight of carrying every ABI.
const strip = (x) =>
    Array.isArray(x) ? x.map(strip)
        : (x && typeof x === "object"
            ? Object.fromEntries(Object.entries(x)
                .filter(([k]) => k !== "internalType")
                .map(([k, v]) => [k, strip(v)]))
            : x);

const client = JSON.parse(readFileSync(join(root, "deployments/client.json"), "utf8"));

// The consensus topic, if one has been created. Optional on purpose: a checkout
// that has never run `make hcs-topic` still builds all six screens, and the
// Rulebook screen says the topic is not configured rather than throwing at boot.
// Only the three public fields a reader needs are carried; the operator block in
// deployments/hcs.json is not something a page has any use for.
const hcsPath = join(root, "deployments/hcs.json");
const hcs = existsSync(hcsPath)
    ? (({topicId, memo, createdAt}) => ({topicId, memo, createdAt}))(JSON.parse(readFileSync(hcsPath, "utf8")))
    : null;
const abis = {};
for (const name of names) {
    abis[name] = strip(JSON.parse(readFileSync(join(abiDir, name + ".json"), "utf8")));
}

// Every contract address the client can read history for, so a screen naming a
// contract can also name what that contract did. The mirror node takes an EVM
// address as the path segment, so no entity id table has to be kept in step.
// The issuer's live proofs, by KYC epoch, inlined so the first screen of a
// three-screen product is not a wall.
//
// `docs/EVIDENCE.md`: "A judge does not have a proof file. Generating one needs
// the circom toolchain, node 22, and about twenty-three seconds per address."
// These are the proofs `make prove-live` already produced for the three live
// addresses; they are real, they verify on chain, and shipping them costs a few
// kilobytes in a document that is already a quarter of a megabyte. Fetching them
// at run time was the alternative and it is worse: the client is six static
// files with no backend, and a demonstration must not depend on a second request
// resolving.
//
// Keyed by the epoch the proof pins in public signal 3. `register` refuses a
// proof for the wrong epoch, so the page has to pick by the registry's own
// answer rather than by whichever file was newest.
const proofFiles = {7: "deployments/proofs-live.json", 8: "deployments/proofs-live-epoch8.json"};
const demoProofs = {};
for (const [epoch, rel] of Object.entries(proofFiles)) {
    const full = join(root, rel);
    if (!existsSync(full)) continue;
    demoProofs[epoch] = JSON.parse(readFileSync(full, "utf8"));
}

const bundle =
    "// Generated by tools/gen-app.mjs. Do not hand edit.\n" +
    "const CLIENT = " + JSON.stringify(client) + ";\n" +
    "const ABI = " + JSON.stringify(abis) + ";\n" +
    "const HCS = " + JSON.stringify(hcs) + ";\n" +
    "const DEMO_PROOFS = " + JSON.stringify(demoProofs) + ";\n";

writeFileSync(join(root, "tools/client-bundle.mjs"), bundle);
mkdirSync(join(root, "app"), {recursive: true});

for (const name of ["index", "prove", "trade", "position", "venue", "repo"]) {
    build("app/" + name + ".template.html", "app/" + name + ".html");
}
