// Builds the three live screens (and the door page) from templates.
// Reads deployments/client.json and deployments/abi/*; writes tools/client-bundle.mjs
// then inlines via tools/gen-page.mjs. Does not edit existing generators or Solidity.
import {readFileSync, writeFileSync, mkdirSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";
import {build} from "./gen-page.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const names = [
    "MatchingEngine",
    "RegistrationGate",
    "ZkKycRegistry",
    "IHoldByPartition",
    "IAtsToken",
    "MarginWatch",
    "ParameterRoot",
    "TradingHalt",
];

const client = JSON.parse(readFileSync(join(root, "deployments/client.json"), "utf8"));
const abis = {};
for (const name of names) {
    abis[name] = JSON.parse(readFileSync(join(root, "deployments/abi", name + ".json"), "utf8"));
}

const bundle =
    "// Generated by tools/gen-app.mjs. Do not hand edit.\n" +
    "const CLIENT = " + JSON.stringify(client) + ";\n" +
    "const ABI = " + JSON.stringify(abis) + ";\n";

writeFileSync(join(root, "tools/client-bundle.mjs"), bundle);
mkdirSync(join(root, "app"), {recursive: true});

for (const name of ["index", "prove", "trade", "position"]) {
    build("app/" + name + ".template.html", "app/" + name + ".html");
}
