// The index: the topic, projected once, committed, and extended from its tail.
//
//   node tools/hcs-index.mjs            # extend deployments/hcs-index.json from where it stopped
//   node tools/hcs-index.mjs --check    # rebuild from sequence 1 and compare with the committed file
//
// HCS is an ordered record, not a database. To know what the topic says a
// reader has to replay it, and replaying a topic from sequence one on every
// page load is the pattern that works at 137 messages and fails at 50,000. So
// the replay happens here, once, and the result is committed the way
// `deployments/client.json` is: an artefact the app builds from offline, moved
// on purpose and never by a page.
//
// The Issuer screen boots from this file's compact form and reads only the
// messages after `throughSequence` off the mirror node. `tools/hcs-verify.mjs`
// rebuilds the projection from the topic and refuses a committed file that
// disagrees. `--check` here is the same comparison, without the chain reads,
// for the moment before committing.
//
// Extending rather than rebuilding is safe because `tools/hcs-project.mjs`
// promises that `extend(project(a), b)` is `project(a ++ b)`, and the vectors
// hold it to that. It is also checked live: the mirror node's `running_hash`
// at `throughSequence` is fetched back before a tail is appended, so a file
// whose head the network does not recognise is refused rather than grown.
import {writeFileSync, readFileSync, existsSync} from "node:fs";
import {join} from "node:path";
import {ROOT, client, mirror, paged, readTopic} from "./hcs-chain.mjs";
import {project, extend, empty, same, comparable} from "./hcs-project.mjs";

// Not exported: this file runs when imported, and a module with that side
// effect must never be something another tool imports for a constant.
// `tools/hcs-verify.mjs` spells the path out for itself.
const INDEX_PATH = join(ROOT, "deployments/hcs-index.json");

const args = process.argv.slice(2);
const CHECK = args.includes("--check");

const NOTE = "Generated by tools/hcs-index.mjs. The consensus topic, replayed in sequence order and folded " +
    "into what a reader asks of it. The topic is the record; this is a projection of it, and " +
    "tools/hcs-verify.mjs rebuilds it from the mirror node and fails if the two disagree. " +
    "Extend with `make hcs-index`; check with `make hcs-index MODE=check`.";

const c = client();
const topic = readTopic();
if (!topic || !topic.topicId) {
    console.error("no deployments/hcs.json. Run `make hcs-topic` first.");
    process.exit(1);
}
const base = `/api/v1/topics/${encodeURIComponent(topic.topicId)}/messages`;

function readIndex() {
    if (!existsSync(INDEX_PATH)) return null;
    const j = JSON.parse(readFileSync(INDEX_PATH, "utf8"));
    if (j.topicId !== topic.topicId) {
        console.error(`the index names topic ${j.topicId}, the record names ${topic.topicId}. Refusing to extend it.`);
        process.exit(1);
    }
    return j;
}

/// The message at one sequence number, or null when the mirror node has none.
async function messageAt(seq) {
    try {
        return await mirror(c.network.mirror, `${base}/${seq}`);
    } catch (e) {
        if (/answered 404/.test(e.message)) return null;
        throw e;
    }
}

const plural = (n, word) => `${n} ${word}${n === 1 ? "" : "s"}`;

function summarise(p, added) {
    console.log(`topic ${topic.topicId}: ${plural(p.messages, "message")} through sequence ${p.throughSequence}` +
        (added === null ? "" : `, ${plural(added, "message")} added`) +
        (p.unreadable.length ? `, ${p.unreadable.length} unreadable` : ""));
    console.log("  " + (Object.entries(p.kinds).map(([k, n]) => `${n} ${k}`).join(", ") || "no readable record yet"));
    for (const src of Object.keys(p.coverage).sort()) {
        const cov = p.coverage[src];
        const latest = p.latest[src];
        console.log(`  ${src}: anchored through ${cov.anchoredThrough ?? "nothing"}` +
            `, checkpoints at ${cov.checkpointEpochs.map(([a, b]) => (a === b ? a : `${a}-${b}`)).join(", ") || "none"}` +
            (latest ? `, latest ${latest.kind} at sequence ${latest.seq}` : ""));
    }
    console.log(`  digest ${p.digest}`);
}

async function build() {
    const prev = readIndex();
    let p = prev ? prev : empty(topic.topicId);
    if (prev && prev.throughSequence > 0) {
        // The head the file claims has to be the head the network has. A
        // running hash the mirror node does not recognise means the file was
        // built off another topic, another mirror, or an edit, and none of
        // those is something to append to.
        const head = await messageAt(prev.throughSequence);
        if (!head) {
            console.error(`the index ends at sequence ${prev.throughSequence}, which the mirror node does not have.`);
            process.exit(1);
        }
        if (prev.runningHash !== null && head.running_hash !== prev.runningHash) {
            console.error(`the index's running hash at sequence ${prev.throughSequence} is not the mirror node's. ` +
                `Refusing to extend it; delete deployments/hcs-index.json to rebuild from sequence 1.`);
            process.exit(1);
        }
    }
    // `gte:` rather than `gt:` because the mirror node refuses `gt:0`, and an
    // empty index has to be able to ask for everything from sequence one.
    const tail = await paged(
        c.network.mirror,
        `${base}?order=asc&limit=100&sequencenumber=gte:${p.throughSequence + 1}`,
        "messages");
    p = extend(p, tail);
    p.builtAt = new Date().toISOString();
    const out = {note: NOTE, ...p};
    writeFileSync(INDEX_PATH, JSON.stringify(out, null, 1) + "\n");
    summarise(p, tail.length);
    console.log(`wrote ${INDEX_PATH}`);
}

async function check() {
    const committed = readIndex();
    if (!committed) {
        console.error("no deployments/hcs-index.json to check. Run `make hcs-index` first.");
        process.exit(1);
    }
    const all = await paged(c.network.mirror, `${base}?order=asc&limit=100`, "messages");
    const head = all.length ? Number(all[all.length - 1].sequence_number) : 0;
    const through = Number(committed.throughSequence) || 0;
    const failures = [];
    const say = (name, pass, detail) => {
        console.log(`${pass ? "pass" : "FAIL"}  ${name}${detail ? "  " + detail : ""}`);
        if (!pass) failures.push(name);
    };

    say("the index does not claim messages the topic lacks", through <= head,
        `index through ${through}, topic head ${head}`);
    const prefix = all.slice(0, through);
    const rebuilt = project(topic.topicId, prefix);
    say("the committed digest is the digest of the topic's bytes", rebuilt.digest === committed.digest,
        `rebuilt ${rebuilt.digest}`);
    const last = prefix[prefix.length - 1];
    say("the committed running hash is the mirror node's at that sequence",
        (last ? last.running_hash : null) === committed.runningHash,
        last ? `mirror ${last.running_hash}` : "no messages");
    say("the committed projection is the projection of the topic", same(rebuilt, committed),
        same(rebuilt, committed) ? "" : firstDifference(comparable(rebuilt), comparable(committed)));
    if (through < head) {
        console.log(`note  the topic has ${plural(head - through, "message")} after the index; run \`make hcs-index\` to extend it`);
    }
    console.log(failures.length
        ? `\n${plural(failures.length, "check")} failed. The index is not the topic.`
        : `\nthe index is the topic through sequence ${through}`);
    process.exit(failures.length ? 1 : 0);
}

/// The first top-level field whose serialisation differs, for a message that
/// names where to look rather than two hundred kilobytes of JSON.
function firstDifference(a, b) {
    for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) {
        const x = JSON.stringify(a[k]);
        const y = JSON.stringify(b[k]);
        if (x !== y) return `${k}: rebuilt ${String(x).slice(0, 80)}, committed ${String(y).slice(0, 80)}`;
    }
    return "";
}

try {
    if (CHECK) await check();
    else await build();
} catch (e) {
    console.error("\n" + e.message);
    process.exitCode = 1;
}
