// Create the venue's consensus topic. Run once, ever.
//
//   node tools/hcs-topic.mjs            # create, refusing if one already exists
//   node tools/hcs-topic.mjs --show     # print what deployments/hcs.json holds
//
// ## The two keys, and why one of them is absent
//
// **Submit key: the operator's.** Anyone may read the topic; only the venue may
// write to it. Without one, a third party could interleave records into the
// venue's own receipt stream, and a stream anyone can write to is not a receipt.
//
// **Admin key: none.** A topic with an admin key can have its memo rewritten,
// its submit key rotated, and the whole topic deleted, all by whoever holds that
// key. That would put "the operator can destroy the record" next to "the
// operator cannot forge a record" in the trust table, and the second claim is
// worth more than the convenience the first buys. So the topic is created
// immutable: this venue cannot delete it, cannot rename it, and cannot change
// who may write to it. What the operator keeps is exactly the power the scope
// admits to, which is the power to stop.
//
// The cost is that a leaked submit key cannot be rotated. That is survivable
// here for the reason the whole design turns on: `tools/hcs-verify.mjs` checks
// every record against the chain, so a record written by somebody else fails the
// same test a forged one would, and the failure is visible to the reader rather
// than to us.
import {writeFileSync} from "node:fs";
import {
    Client, PrivateKey, AccountId, Hbar,
    TopicCreateTransaction, TopicInfoQuery,
} from "@hiero-ledger/sdk";
import {env, client, TOPIC_RECORD as RECORD, TOPIC_MEMO as MEMO, readTopic as readRecord}
    from "./hcs-chain.mjs";

const args = process.argv.slice(2);
const has = (f) => args.includes(f);

if (has("--show")) {
    const r = readRecord();
    if (!r) {
        console.error("no deployments/hcs.json yet. Run `make hcs-topic`.");
        process.exit(1);
    }
    console.log(JSON.stringify(r, null, 1));
    process.exit(0);
}

const existing = readRecord();
if (existing && existing.topicId) {
    console.error(
        `deployments/hcs.json already names topic ${existing.topicId}.\n` +
        "A second topic would split the record in two and neither would be the venue's.\n" +
        "Delete the file by hand if that is genuinely what you want.");
    process.exit(1);
}

const e = env(["HEDERA_ACCOUNT_ID", "HEDERA_PRIVATE_KEY"]);
const c = client();

// ECDSA, because the account that pays for this is the same EVM account that
// deployed the venue. An ED25519 key here would create a topic nobody in this
// repository can submit to.
const key = PrivateKey.fromStringECDSA(e.HEDERA_PRIVATE_KEY);
const operator = AccountId.fromString(e.HEDERA_ACCOUNT_ID);
const hedera = Client.forName(c.network.chainId === 295 ? "mainnet" : "testnet")
    .setOperator(operator, key);

try {
    const tx = await new TopicCreateTransaction()
        .setTopicMemo(MEMO)
        .setSubmitKey(key.publicKey)
        .setMaxTransactionFee(new Hbar(5))
        .execute(hedera);
    const receipt = await tx.getReceipt(hedera);
    const topicId = receipt.topicId.toString();

    // Read it straight back rather than trusting the receipt: the two keys are
    // the whole security argument above, and an argument nobody checked is a
    // claim. `adminKey` must be absent and `submitKey` must be ours.
    const info = await new TopicInfoQuery().setTopicId(receipt.topicId).execute(hedera);
    const submit = info.submitKey ? info.submitKey.toString() : null;
    const want = key.publicKey.toString();
    if (info.adminKey) throw new Error(`the topic came back with an admin key: ${info.adminKey}`);
    if (submit !== want) throw new Error(`the topic's submit key is ${submit}, not the operator's`);
    if (info.topicMemo !== MEMO) throw new Error(`the topic's memo is ${JSON.stringify(info.topicMemo)}`);

    const record = {
        note: "Generated by tools/hcs-topic.mjs. The venue's consensus topic, created once.",
        createdAt: new Date().toISOString(),
        topicId,
        memo: MEMO,
        network: {
            chainId: c.network.chainId,
            mirror: c.network.mirror,
            explorer: c.network.explorer,
        },
        operator: {
            accountId: e.HEDERA_ACCOUNT_ID,
            evmAddress: e.HEDERA_EVM_ADDRESS || null,
            note: "Holds the submit key. Cannot delete, rename or reassign the topic: it was created with no admin key.",
        },
        keys: {adminKey: null, submitKey: want},
        transactionId: tx.transactionId.toString(),
        hashscan: `${c.network.explorer}/topic/${topicId}`,
        publishes: {
            engine: c.addresses.MatchingEngine,
            vault: c.addresses.RepoVault,
        },
    };
    writeFileSync(RECORD, JSON.stringify(record, null, 1) + "\n");
    console.log(`topic ${topicId} created, submit key ours, no admin key`);
    console.log(record.hashscan);
} finally {
    hedera.close();
}
