// The client half of `DisclosureLattice`, `DisclosureBudget` and the meter's
// spend rule. Vectors live in `tools/lattice.test.mjs`; `test/ReceiptVectors.t.sol`
// asserts the same literals against the deployed getters, so the receipt page
// and the venue cannot drift about what a disclosure cost.
//
// Only what a receipt needs is ported. The lattice's hygiene half (`close`,
// `isIdeal`) validates policies at adoption and never runs client side, and
// `lexSummary` exists on chain only to be compared against and is documented
// "do not gate on it", so neither is here.

export const G = {NONE: 0, PRED: 1, AGG: 2, BUCKET: 3, EXACT: 4};
export const T = {PRE: 0, IMM: 1, M15: 2, EOD: 3, EPOCH: 4, NEVER: 5};
export const G_CARD = 5, T_CARD = 6;
export const TOP = 0x3fffffff, BOTTOM = 0;

const ROW = 0x3f;

/// The principal ideal generated by one disclosure. An observer who learns `g`
/// at `t` also learns anything coarser and anything later, and the cell is that
/// whole set. `DisclosureLattice.point`.
export function point(g, t) {
    if (g >= G_CARD) throw new RangeError("granularity " + g);
    if (t >= T_CARD) throw new RangeError("time " + t);
    const later = BigInt(ROW & ~((1 << t) - 1));
    const rows = ((1n << BigInt(6 * (g + 1))) - 1n) / 63n;
    return Number(later * rows);
}

/// True when `actual` stays under `ceiling`. One OR and one comparison, which is
/// the gate that makes a matrix cell enforceable rather than aspirational.
export const permits = (ceiling, actual) => ((actual | ceiling) >>> 0) === ceiling >>> 0;

/// The cells by which `actual` exceeds `ceiling`. Empty iff permitted.
export const excess = (ceiling, actual) => (actual & ~ceiling) >>> 0;

/// The earliest time anything at all is learned, or null for an empty ideal.
/// A ceiling stated only in granularity cannot express "not before end of day",
/// which is the defect the ideal representation removes.
export function earliest(x) {
    for (let t = 0; t < T_CARD; t++) {
        for (let g = 0; g < G_CARD; g++) {
            if ((x >>> (g * T_CARD + t)) & 1) return t;
        }
    }
    return null;
}

/// Bits one observer learns at granularity `g`. `DisclosureBudget.bits`.
export function bits(row, g) {
    if (g === G.NONE) return 0;
    if (g === G.PRED) return 1;
    if (g === G.AGG) return row.aggBits;
    if (g === G.BUCKET) return row.bucketBits;
    if (g === G.EXACT) return row.domainBits;
    throw new RangeError("granularity " + g);
}

/// The smallest coalition at `g` that breaks the budget. Zero when no coalition
/// of that level ever does. `DisclosureBudget.breakingSize`.
export function breakingSize(row, g) {
    if (row.budgetBits === 0) return 0;
    const per = bits(row, g);
    if (per === 0) return 0;
    const n = Math.floor(row.budgetBits / per) + 1;
    if (per * n > row.domainBits && row.domainBits <= row.budgetBits) return 0;
    return n;
}

/// A row is metered only when governance published a bound for it. Zero reads
/// "no bound published", never "the bound is zero": `requireWellFormed` refuses
/// `budgetBits >= domainBits` and `adopt` refuses a budget on a row whose
/// ceiling admits exact.
export const isMetered = (row) => row.budgetBits !== 0;

/// One charged disclosure, Rule A. Never fails the action: an exhausted budget
/// withholds the venue's speech and lets the state transition stand, because a
/// compliant transfer must not revert because the venue ran out of things it may
/// say. `DisclosureMeter.spend`.
///
/// Returns what a receipt has to print, which is more than the contract returns:
/// the contract answers `afforded` and the reader needs to know what it cost and
/// what is left.
export function spend(row, spent, g) {
    if (!isMetered(row)) return {afforded: true, cost: 0, spentAfter: spent, metered: false};
    const cost = bits(row, g);
    if (spent + cost > row.budgetBits) {
        return {afforded: false, cost, spentAfter: spent, metered: true};
    }
    return {afforded: true, cost, spentAfter: spent + cost, metered: true};
}

/// The five getters, against one row, as one object. This is the receipt: it is
/// `ceilingFor`, `wouldDisclose`, `spentBits`, `wouldAfford` and `breakingSize`,
/// which is every question the venue can be asked about what it just published.
export function receiptFor(ceiling, row, spent, g, t) {
    const asked = point(g, t);
    const over = excess(ceiling, asked);
    return {
        ceiling,
        asked,
        permitted: over === 0,
        excess: over,
        earliest: earliest(ceiling),
        metered: isMetered(row),
        budgetBits: row.budgetBits,
        spentBits: spent,
        cost: isMetered(row) ? bits(row, g) : 0,
        wouldAfford: !isMetered(row) || spent + bits(row, g) <= row.budgetBits,
        breakingSize: breakingSize(row, g),
    };
}
