set -e
D="$(cd "$(dirname "$0")" && pwd)"; cd "$D/fv"
RPC=http://127.0.0.1:8545
K=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
S1="verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[1])"
S5="verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[5])"
SC="verify(uint256[2],uint256[2][2],uint256[2],uint256[1])"
eval "$(cat "$D/args.env")"
BOUND=200000
dep() { cast send --rpc-url $RPC --private-key $K --json --create \
        "$(jq -r '.bytecode.object' out/$1.sol/$1.json)$2" | jq -r '.contractAddress.gasUsed' | tr '\n' ' '; }
read TV TVG <<< "$(dep TrivialVerifier)"
read FV FVG <<< "$(dep FiveVerifier)"
read AV AVG <<< "$(dep AbsentPairingVerifier)"
CT=$(cast abi-encode "c(address,uint256)" $TV $BOUND | sed 's/^0x//')
read CV CVG <<< "$(dep CappedVerifier $CT)"
read GV GVG <<< "$(dep GuardedVerifier $CT)"

echo "Spike 1 stage 2 gas, taken from anvil transaction receipts (cancun, tx gas"
echo "limit 15,000,000 to match Hedera's contract call ceiling). No gasleft()."
echo "Generated by gasrun.sh; every number is receipt.gasUsed."
echo
echo "deployment                      gas"
printf "  %-30s %s\n" "Groth16Verifier (1 signal)"  $((TVG))
printf "  %-30s %s\n" "Groth16Verifier (5 signals)" $((FVG))
printf "  %-30s %s\n" "CappedVerifier"              $((CVG))
printf "  %-30s %s\n" "GuardedVerifier"             $((GVG))
echo
row() { local L="$1" TO="$2" SIG="$3"; shift 3
  local RET GAS
  RET=$(cast call --rpc-url $RPC --gas-limit 15000000 "$TO" "$SIG" "$@" 2>&1 | tr -d '\n')
  GAS=$(cast send --rpc-url $RPC --private-key $K --json --gas-limit 15000000 "$TO" "$SIG" "$@" 2>/dev/null | jq -r '.gasUsed // "TX FAILED"')
  local D="?"; case "$RET" in
    *0000000000000000000000000000000000000000000000000000000000000001) D="true";;
    *0000000000000000000000000000000000000000000000000000000000000000) D="false";;
  esac
  case "${#RET}" in 130) case "$RET" in *00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001) D="ran=true  ok=true";; *00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000) D="ran=true  ok=false";; *) D="ran=false ok=false";; esac;; esac
  printf "  %-32s %-10s %s\n" "$L" "$((GAS))" "$D"
}
echo "generated verifier, unmodified   gas        returns"
row "valid proof"            $TV "$S1" "${T_VALID[@]}"
row "A negated (on curve)"   $TV "$S1" "${T_NEGA[@]}"
row "wrong public signal"    $TV "$S1" "${T_WRONGSIG[@]}"
row "public signal == r"     $TV "$S1" "${T_SIGATR[@]}"
row "A off curve (1,1)"      $TV "$S1" "${T_OFFCURVE[@]}"
echo
echo "5 public signals"
row "valid proof"            $FV "$S5" "${F_VALID[@]}"
echo
echo "0x08 modelled as codeless (fail open)"
row "forged A=(1,1)"         $AV "$S1" "${T_OFFCURVE[@]}"
row "genuine proof"          $AV "$S1" "${T_VALID[@]}"
echo
echo "CappedVerifier, bound $BOUND"
row "valid proof"            $CV "$SC" "${T_VALID[@]}"
row "A negated"              $CV "$SC" "${T_NEGA[@]}"
row "A off curve (1,1)"      $CV "$SC" "${T_OFFCURVE[@]}"
echo
echo "GuardedVerifier, on-curve check then capped call, bound $BOUND"
row "valid proof"            $GV "$SC" "${T_VALID[@]}"
row "A negated"              $GV "$SC" "${T_NEGA[@]}"
row "wrong public signal"    $GV "$SC" "${T_WRONGSIG[@]}"
row "A off curve (1,1)"      $GV "$SC" "${T_OFFCURVE[@]}"
